### ISSUE TITLE
Restoring a previously saved perspective does not (entirely) work

### ISSUE THREAD

**Issue by carstenfuchs** [nhold/wxWidgets#104]
(Originally reported at https://groups.google.com/d/msg/wx-dev/EL-PcSMc9A8/4vtBAUicHQAJ)

Using commit 7697ea6 of 2015-07-23, saving a perspective into a string, then restoring the perspective from the string seems not to work entirely. For example, in my main window's constructor I use this code:

``` c++
    // Save the AUI perspective that we set up in this ctor code as the
    // "default perspective".
    m_AUIDefaultPerspective = m_AUIManager.SavePerspective();

    // Load the AUI user perspective (implies a call to m_AUIManager.Update()).
    m_AUIManager.LoadPerspective(
        wxConfigBase::Get()->Read("MapEditor_AUIUserPerspective", m_AUIDefaultPerspective));
```

This used to work in "old" wxAUI code, but somehow "loses" one of the child panes in the new wxAUI. It also works normally if the above two lines are replaced by a simple  m_AUIManager.Update();  .

I'll try to reproduce this in wxAUI sample, then update here accordingly.

**Comment by mjmacleod** [comment]
Thanks, will what for the additional info then let us know how it goes :)

**Comment by carstenfuchs** [comment]
Good news, at least in my program I could pin the problem. In the parent window's ctor, this is the relevant portion of the pane setup:

``` c++
    // [......]

    m_AUIManager.AddPane(
        Pane1,
        wxAuiPaneInfo().
            // Name("xy").
            Caption("some caption").
            DestroyOnClose().Right().Row(1).Position(0).MaximizeButton().MinimizeButton());

    m_AUIManager.AddPane(
        ThePaneThatGetsLost,
        wxAuiPaneInfo().
            // Name("xy").
            Caption("another caption").
            DestroyOnClose().Right().Row(1).Position(1).MaximizeButton().MinimizeButton());
```

In my code, the Name(...) settings were actually commented out. If I comment them in, using a unique name for each, the problem does not occur!  :-)

**Comment by mjmacleod** [comment]
Hrm, okay.
So we should look then I guess into what is happening when no name is assigned that is different than before.

**Comment by mjmacleod** [comment]
Okay - I can reproduce this in the sample, it only happens if there are 2 or more panes without names, in which case the first of the two panes seems to vanish, I'll dig a bit and see what original aui did differently here.

**Comment by mjmacleod** [comment]
Righto - Try the above out and let me know if it works.

**Comment by nhold** [comment]
This was actually my fault when merging branches, that process was pretty difficult and unfortunately I did make some mistakes so thanks for figuring that out Malcolm.

**Comment by mjmacleod** [comment]
No worries, the merge was always going to be difficult and introduce new bugs no matter who did it...

If one wants to find fault I guess it lies with me for not pushing this more aggressively while the code was still 'fresh' after GSOC, or the wx devs for completely bungling multiple opportunities to move this into the main code base where things could have been easier managed.

Though none of that is productive, lets just try get to a point where the merge can happen :)

**Comment by carstenfuchs** [comment]
Tested, it works very well!   :-)

Many thanks to everyone for your efforts!

**Comment by mjmacleod** [comment]
Great - Nathan, please accept the pull request when you get a chance :)
