### ISSUE TITLE
Assert on dragging one tab over another when "Allow Floating" is disabled

### ISSUE THREAD

**Issue by pkulchenko** [nhold/wxWidgets#115]
This can be seen in Auidemo sample:
1. Start the example
2. Uncheck `Manager Options | Allow Floating`
3. Try to drag `Floatable pane 2` over `Floatable5` tab.

When the mouse is moved over `Floatable5` tab (while dragging), the assert is thrown: `./src/aui/framemanager.cpp(2739): assert "Assert failure" failed in LayoutAddDock(): Flag optionActiveNotebook should not be defined to several wxAuiPaneInfo`. This is on Windows (commit a7976ec).

**Comment by Kinaou** [comment]
It seems to be the same issue than https://github.com/nhold/wxWidgets/issues/122. Removing the assert resolves also this issue.

**Comment by pkulchenko** [comment]
Closing as duplicate of #122.
