### ISSUE TITLE
pane(tab) with icon in notebook.

### ISSUE THREAD

**Issue by nhold** [nhold/wxWidgets#14]
A tab that has an icon on a notebook does not render correctly.

![tabwithimagefails](https://f.cloud.github.com/assets/1107474/1014740/453781e2-0bc5-11e3-9f33-508e361bd7c7.PNG)

**Comment by ghost** [comment]
Nathan, have you checked the fix for this one ? The icons should no more be cut off by making their tab big enough to fit them.

**Comment by nhold** [comment]
Yes this is fixed now!
