### ISSUE TITLE
Incorrect showing of active \ inactive pane

### ISSUE THREAD

**Issue by nhold** [nhold/wxWidgets#18]
Currently it is impossible to tell what pane is currently active, as all panes have a blue title bar except whatever one was last moved onto the auimanaged frame.

**Comment by ghost** [comment]
There is another point that is not clear about pane activation: we now mark a pane as activated either by program or when the user clicks on the pane's title ... But when we click on a control or any sub-window of a pane, the pane does not get activated. Should activation follow the focus of the windows contained in a pane ? I tend to say yes, but what is your opinion about this ?

**Comment by Kinaou** [comment]
It seems logical to me also, but it is not the current behavior for the 'unpatched' aui version. I do not know if there is a particular reason...

**Comment by nhold** [comment]
I think it is logical as well, we will add it for now and see what Vadz says when he reviews it.
