### ISSUE TITLE
Aui toolbars are not restored properly (buttons disappears and  > other glitches) 

### ISSUE THREAD

**Issue by nhold** [nhold/wxWidgets#2]

**Comment by ghost** [comment]
When restoring the perspective with wxAui toolbars, I used to get this:
![toolbars_ok](https://f.cloud.github.com/assets/2693550/834660/54c384c4-f2c7-11e2-906b-2131c0031ade.png)

And now, I get that:
![toolbars_truncated](https://f.cloud.github.com/assets/2693550/834663/61c4e71c-f2c7-11e2-9f70-85342cf1c96e.png)

Each toolbar recover it's correct size as soon as it is moved

**Comment by ghost** [comment]
This comes from a missing semicolon in the saved perspective string that prevent the restoration of the bestw field.
