### ISSUE TITLE
Icon is not copied at the PaneInfo object copy

### ISSUE THREAD

**Issue by Kinaou** [nhold/wxWidgets#21]
The icon defined in the PaneInfo object is not copied by the copy constructor and assignment operator. Therefore the docked panes icon is not displayed.
Perhaps it would be fine to check if other elements are not missing.

**Comment by ghost** [comment]
Kinaou, can you review the last fixes I've made and close the tickets if possible ?

**Comment by nhold** [comment]
I can close it for you, it looks okay to me. I assume the main part is line 195?

**Comment by ghost** [comment]
Yes, it's that. Thank you.

**Comment by Kinaou** [comment]
It works, thank you !
