### ISSUE TITLE
Icon not updated dynamically for docked panes

### ISSUE THREAD

**Issue by Kinaou** [nhold/wxWidgets#23]
While setting a new icon through `wxAuiPaneInfo::SetIcon` and `wxAuiPaneInfo::SetBitmap` updates dynamically the `wxAuiNotebook` tab icon (after `wxAuiManager::Update` call), it is not the case for the title bar of a docked pane.

**Comment by ghost** [comment]
This works for me, at least with the latest fixes I made. Could you try again please ?

**Comment by nhold** [comment]
This works for me also, great work laurent!

**Comment by Kinaou** [comment]
It's OK, it works, thank you !
