### ISSUE TITLE
Cannot create a notebook programmatically

### ISSUE THREAD

**Issue by Kinaou** [nhold/wxWidgets#25]
I have not found how to create a notebook directly by adding the panes with a PaneInfo definition.
I tried to set the same layer, position and row in the PaneInfo object but the pane is systematically created next to the last created pane and never in a notebook.

**Comment by ghost** [comment]
Addition of the new API xAuiPaneInfo::MoveOver(const wxAuiPaneInfo &target) to allow stacking panes in noetbooks by program.
Kinaou, would you check it works for you ?

**Comment by nhold** [comment]
This looks okay to me, will re-open if needed.

**Comment by Kinaou** [comment]
It's OK, it works, thank you !
