### ISSUE TITLE
wxAuiNotebook fails to draw the tabs when the notebook has 1 page

### ISSUE THREAD

**Issue by robertop** [nhold/wxWidgets#33]
1. Run the aui sample
2. close all of the tabs except the tab labeled "wxTextCtrl1" in the center notebook.

See that the center notebook no longer shows tabs.

Running the aui sample from master shows the proper behavior.

Tested commit  0e3924e0db169be04e6d843d345c57aaf1ca5ee9
on ubuntu linux 12.04

**Comment by ghost** [comment]
I ran in several other problems with the wxAui demo on Linux. Did you compiled with GTK 2 or GTK 3 ?

**Comment by robertop** [comment]
I compiled using gtk2

**Comment by ghost** [comment]
This one is fixed in the latest version. Can you check back and close ?

**Comment by robertop** [comment]
Hi,
I pulled the latest and tried to compile, but compilation failed.  I attempted to compile for the GTK 2 platform. The compilation errors are:

```
./src/aui/tabartgtk.cpp:290:61: error: ‘const class wxAuiPaneInfo’ has no member named ‘GetBitmap’
./src/aui/tabartgtk.cpp:429:14: error: ‘const class wxAuiPaneInfo’ has no member named ‘GetBitmap’
./src/aui/tabartgtk.cpp:434:57: error: ‘const class wxAuiPaneInfo’ has no member named ‘GetBitmap’
./src/aui/tabartgtk.cpp:442:28: error: ‘const class wxAuiPaneInfo’ has no member named ‘GetBitmap’
./src/aui/tabartgtk.cpp:447:23: error: ‘const class wxAuiPaneInfo’ has no member named ‘GetBitmap’
```

I did a bit of bisecting and it seems that wxAuiPaneInfo::GetBitmap was renamed to wxAuiPaneInfo::GetIcon  in commit 35fc433bfca5779dd699951c3c42acc424bb7496

**Comment by ghost** [comment]
Unfortunatly the patch for this is still in a pull request. Please try again after Nathan had merged the pending code. Sorry for that ...

**Comment by ghost** [comment]
It's ok now: the patch has been merged and you can test safely

**Comment by nhold** [comment]
Am closing, but only tested on arch, 64bit gtk2 if it's still happening Robertop just reopen.
