### ISSUE TITLE
Graphical glitches on tabs

### ISSUE THREAD

**Issue by ghost** [nhold/wxWidgets#46]
There are small graphical glitches on tab drawing in the new dynamic branch. These glitches are both on Windows and GTK. Here are some screenshots (good 1rst, bad 2nd) taken from Linux/GTK2 on the sample.
On the glossy theme:
![glossy_good](https://cloud.githubusercontent.com/assets/2693550/2935436/e999a452-d80e-11e3-8578-3f7253e52399.png)
![glossy_bad](https://cloud.githubusercontent.com/assets/2693550/2935438/f34046f0-d80e-11e3-963c-9d1c6a3acac0.png)

We can see an unwanted thin black border and something looking as a second border over the first one in the inner frame.

Now on the simple theme:
![simple_good](https://cloud.githubusercontent.com/assets/2693550/2935444/26370986-d80f-11e3-8db0-f962d2cabc18.png)
![simple_bad](https://cloud.githubusercontent.com/assets/2693550/2935446/2aff833a-d80f-11e3-9c1e-203c6acdeb49.png)

We  see the same thin external black frame, and that the inner frame is not drawn past the last tab (and in fact not before the first one if the left arrow is present).

**Comment by mjmacleod** [comment]
The black border is coming from the wxAuiNotebook itself - if I hard code it to use wxBORDER_NONE as the style then it goes away.
I'm not 100% sure what should happen here - is this just a bug in the sample because it sets a border style, or should AUI be stripping border styles?

**Comment by ghost** [comment]
Well, it's a good question. We should be as much as possible a drop in replacement of the legacy AUI, so I would tend to say we have to force the wxBORDER_NONE style.

**Comment by mjmacleod** [comment]
Okay, I'm going to send a pull request to fix the black border issue - I can't see the other glossy issue, and I'm not sure about the other simple notebook issue (except that it certainly doesn't seem like a major issue to me) - Jens Lody may be better qualified to know what has changed there though.

**Comment by mjmacleod** [comment]
GetBestTabCtrlSize was not being called on the gtk tab art provider because it had not been updated to match the other virtual methods - this may explain some of the above possibly?
I've added it to my pull request.

**Comment by ghost** [comment]
Just for more information, here is a screenshot of the problem under Win7
![tabglitchwin7](https://cloud.githubusercontent.com/assets/2693550/2945009/0fd4b7aa-d9dc-11e3-9e7b-69a4455b2cd3.png)
You see the black line not going beyond the last tab

**Comment by ghost** [comment]
The latest code fixes the black border issue, but the problems on the tab themselves are still there. It looks like if the width of the pane is not taken in account when drawing the border part on each side of the tabs.

Another strange thing is that the generic theme is not affected by this glitch ...

**Comment by ghost** [comment]
Another glitch on windows: we have no more black borders, but grey borders  around the inner pane area ! I definetly have to understand what's going on with that !
![grey_glitch](https://cloud.githubusercontent.com/assets/2693550/2957164/2dc45cc4-da9b-11e3-8d15-52521d101e6f.png)

**Comment by mjmacleod** [comment]
Try stripping the border from all windows as they are added to AUI and see if that helps. That should at least show whether the border is coming from the child panes or somewhere else.

**Comment by ghost** [comment]
It's a good idea, I will try this qucikly. While investigating a bit further, I came to the conclusion that we have here in fact two issues: one for the inner frame of dynamically created notebooks, and one on the drawing of the tabs.

**Comment by ghost** [comment]
Well I removed the borders of the windows but the grey border remains here :( It's only in the dynamically created panes, not on wxAuiNotebook panes, which is strange as they are almost handled the same way.

**Comment by mjmacleod** [comment]
hrm, wonder if this is a symptom of some of the other recent changes, or if it was always there.
It looks almost like the wxAuiManager::Layout code is incorrectly adding borders on either side of the dynamic notebook. Could you maybe try with (038c16f3f15629d8088c2050ef7cf96aed9dc425) from nhold branch - (i.e. before your latest pull changes) - just to verify that this was already an issue before the changes to the Layout code?

**Comment by ghost** [comment]
I will try this tomorrow because meanwhile I came across another serious bug about GetManager(). I also found several places where panes are checked specifically against wxAuiNotebook() to know if they have tabs, instead of using FindTabs(). I think the issue is there with a pane not being processed as a tab pane because it's parent is not a wxAuiNotebook. I'll finish with that tomorrow.

**Comment by ghost** [comment]
The fix in my latest pull request together seems to fix the border problem as far as I can see. Have now to find out why the tabs are not drawn on the full pane width as they used to in legacy wxAui

**Comment by ghost** [comment]
Found and fixed the issue on wxAuiSimpleTabArt :) I have to test under Linux for the remaining one on the glossy theme, but I can't until Saturday.

**Comment by mjmacleod** [comment]
Sounds promising, still waiting for your previous pull to land, but will check things out once they do. I can test Linux this side. Not sure how Nathan is coming along with the sync to wxWidgets-trunk but assuming nothing major comes up this should essentially mean we are basically there.

**Comment by mjmacleod** [comment]
Just one thing - isn't that code only executed if it is a notebook with tabs on the left?
If so isn't it actually just the setting of the pen that is making the difference (In which case the remaining code should remain #if'ed out)?

**Comment by mjmacleod** [comment]
Ergh, sorry nevermind, didn't realise github had collapsed the code block (Still getting used to github), so there is of course if statements as well for the other cases. Looks like that is solved then.

**Comment by nhold** [comment]
Sync to master is going along slowly, there are more than 30 conflicts that can't be auto-fixed and some of the auto-merged ones messed things up. But I am slowly getting there.

**Comment by mjmacleod** [comment]
Okay thanks!

**Comment by mjmacleod** [comment]
Can confirm the wxAuiSimpleTabArt fix seems to work here on GTK.
Glossy theme looks okay to me but maybe I am missing something.
![image](https://cloud.githubusercontent.com/assets/7540840/2974667/d358014a-db8b-11e3-80f8-945cac5473f5.png)

**Comment by ghost** [comment]
Ok, thanks for the test Malcom. I think we can close this one now.
