### ISSUE TITLE
Should be able to drop in center even when center is empty.

### ISSUE THREAD

**Issue by mjmacleod** [nhold/wxWidgets#48]
Currently it is possible to drag the last pane out of the center in some cases, which then leaves the center completely empty with no way to fill it again.

**Comment by ghost** [comment]
It's stange as I made a patch to allow center panes and I use it in my current code. Are you sure all center panes have the center dock direction ? If yes and it still don't work, can you provide a sample  ?

**Comment by ghost** [comment]
Nathan, this one is a duplicate of #24. Can you close it ? Anyway I have no problem with that feature and cannot reproduce it. Can you check again ?
