### ISSUE TITLE
Hint for dropping in notebooks wrong

### ISSUE THREAD

**Issue by mjmacleod** [nhold/wxWidgets#49]
When doing a drop that will forma  new notebook - i.e. no existing notebook - it seems that the code is still subtracting the tab height from the hint rectangle. This leads to confusing hint rectangles.
We need to change the code that does the hint rectangles to check for this case.

**Comment by mjmacleod** [comment]
I see looking closer now that there are various other instances where the drop hint is slightly wrong - it is not as simple as what I sad above.
I can't think why this should be as it uses the same code to determine the hint position as it does to handle the actual drop - there is probably a bug somewhere - if I get some time I will try debug the drop code and see what I can find.

Off the top of my head what I think might be happening is that.
1) The 'fake' hint pane is inserted and Layout is called
2) We are using the position in that Layout to draw the hint
3) But the original window is also still in that Layout so the Layout is not the same as when the final drop is done.
If this is the case then what needs to happen is that the original window must be temporarily removed during the hint layout calculation.

The above is just a guess though based on the symptoms, will have to look closer.

**Comment by mjmacleod** [comment]
The latest pull request should fix most of the drop hint issues, could use some more testing though.

**Comment by ghost** [comment]
It seems to be ok for me, at least under Windows. So maybe we can close this one, knowing that hinting is a part where enhancements would have to be made.
