### ISSUE TITLE
Initial AUI toolbar placed incorrectly

### ISSUE THREAD

**Issue by nhold** [nhold/wxWidgets#5]
Each Aui toolbar is initially placed in a separate tab pane and 
returns to the normal state as soon as moved

**Comment by ghost** [comment]
The toolbars used to be placed as this with current wxAui:
![toolbars_ok](https://f.cloud.github.com/assets/2693550/834641/cc164d64-f2c6-11e2-85e5-cc507a72715d.png)

But with the dynamic wxAui, it is:
![toolbars_aui_0](https://f.cloud.github.com/assets/2693550/834645/de24d07a-f2c6-11e2-80b5-6e4c0bc2fd55.png)

As soon as you move a toolbar, the layout goes back to normal.

**Comment by ghost** [comment]
Nathan, can you close this one ?

**Comment by nhold** [comment]
Yep, sorry had to get back from the US to test.
