### ISSUE TITLE
Need a style flag to enable dynamic notebooks

### ISSUE THREAD

**Issue by ghost** [nhold/wxWidgets#56]
The dynamic notebooks creation is controlled by the wxEVT_AUI_PANE_DOCK_OVER event that defaults to forbid notebooks. This default behavior should be controlled by a wxAuiManager flag to make it more obvious and ease integration in interface code generators such as wxFormBuilder and others

**Comment by ghost** [comment]
The pull request #57 introduces the wxAUI_MGR_NB_ALLOW_NOTEBOOKS flag that set the default behavior to allow the creation of dynamic notebooks in a wxAuiManager.

**Comment by nhold** [comment]
This looks okay.
