### ISSUE TITLE
Changing pane caption colour

### ISSUE THREAD

**Issue by nhold** [nhold/wxWidgets#6]
The background color of the pane caption changes with no apparent 
reason (starts at blue, and turns gray when de-docked and re-docked)

**Comment by ghost** [comment]
The problem can also be shown as follow: Start with a separate pane and some other panes stacked in a notebook:
![caption_color_0](https://f.cloud.github.com/assets/2693550/834770/66110abe-f2ca-11e2-9fdf-48ac7c7c5a9c.png)

Then simply change the selected tab in the notebook, and the caption color of the unrelated pane changes magically (in blue):
![caption_color_1](https://f.cloud.github.com/assets/2693550/834778/8621bbfa-f2ca-11e2-9df7-3f64ff5ef40e.png)

**Comment by nhold** [comment]
Closing because the behaviour is now 'as intended'.
