### ISSUE TITLE
closing AUI notebook pages does not update a notebook's page count

### ISSUE THREAD

**Issue by robertop** [nhold/wxWidgets#75]
The number of pages returned by wxAuiNotebook::GetPageCount() does not decrease when pages in an AUI notebook are closed by the application user. Also, the window that the user closed does not get destroyed.
1. Apply the patch below to the sample
2. compile and run the auidemo
3. Go to view..create wxAuiNotebook
4. close the  tab with the title "wxTextCtrl 1"  on the newly created notebook.
   Notice that the message states "page count=10" and does not decrease as you close pages. Notice that the next message states that the HTML window has not been destroyed (it still exists when looking it up via wxWindow::FindWindowById)
5. Keep on closing tabs. Notice that the notebook size never decreases.

I am not sure if this is a bug or a feature, as notebooks are now dynamically created and they are not  to be relied upon? At the very least, I would think that the windows should still be destroyed though.

Patch is below:

```
diff --git a/samples/aui/auidemo.cpp b/samples/aui/auidemo.cpp
index 12d7776..098a269 100644
--- a/samples/aui/auidemo.cpp
+++ b/samples/aui/auidemo.cpp
@@ -103,6 +103,7 @@ class MyFrame : public wxFrame
         ID_DropDownToolbarItem,
         ID_SampleItem,
         ID_ToggleNB,
+       ID_PageText1,
         ID_FirstPerspective = ID_CreatePerspective+1000
     };

@@ -158,6 +159,7 @@ private:
     void OnUpdateUI(wxUpdateUIEvent& evt);
     void OnToggleNB(wxCommandEvent& WXUNUSED(evt));
     void OnPaneClose(wxAuiManagerEvent& evt);
+   void OnNotebookPageClosed(wxAuiNotebookEvent& event);

 private:

@@ -630,6 +632,7 @@ BEGIN_EVENT_TABLE(MyFrame, wxFrame)
     EVT_MENU_RANGE(MyFrame::ID_FirstPerspective, MyFrame::ID_FirstPerspective+1000, MyFrame::OnRestorePerspective)
     EVT_AUITOOLBAR_TOOL_DROPDOWN(ID_DropDownToolbarItem, MyFrame::OnDropDownToolbarItem)
     EVT_AUI_PANE_CLOSE(MyFrame::OnPaneClose)
+   EVT_AUINOTEBOOK_PAGE_CLOSED(wxID_ANY, MyFrame::OnNotebookPageClosed)
 END_EVENT_TABLE()


@@ -1315,7 +1318,7 @@ wxAuiNotebook* MyFrame::CreateNotebook()
    ctrl->AddPage( panel, wxT("wxPanel"), false, page_bmp );


-   ctrl->AddPage( new wxTextCtrl( ctrl, wxID_ANY, wxT("Some text"),
+   ctrl->AddPage( new wxTextCtrl( ctrl, ID_PageText1, wxT("Some text"),
                 wxDefaultPosition, wxDefaultSize, wxTE_MULTILINE|wxNO_BORDER) , wxT("wxTextCtrl 1"), false, page_bmp );

    ctrl->AddPage( new wxTextCtrl( ctrl, wxID_ANY, wxT("Some more text"),
@@ -1365,3 +1368,17 @@ wxString MyFrame::GetIntroText()
         "</body></html>";
     return wxString::FromAscii(text);
 }
+
+void MyFrame::OnNotebookPageClosed(wxAuiNotebookEvent& event)
+{
+   wxAuiNotebook* ctrl = (wxAuiNotebook*)event.GetEventObject();
+
+    // selection should always be a valid index
+    wxASSERT_MSG( ctrl->GetSelection() < (int)ctrl->GetPageCount(),
+                  wxString::Format("Invalid selection %d, only %d pages left",
+                                   ctrl->GetSelection(),
+                                   (int)ctrl->GetPageCount()) );
+   wxMessageBox(wxString::Format("page count=%ld", ctrl->GetPageCount())); 
+   wxMessageBox(wxString::Format("IDPageText1 found?=%d", wxWindow::FindWindowById(ID_PageText1, ctrl) != NULL));
+    event.Skip();
+}
\ No newline at end of file

```

**Comment by mjmacleod** [comment]
AUI has the pane option optionDestroyOnClose to control his behavior,
can you confirm if it behaves as expected if you manually set this flag
on the panes?

I'm in two minds about this one - deleting the panes by default means
that the deleted panes won't be restored when perspective is restored -
which is probably (in my opinion) the opposite of what most new AUI
users are expecting when they write AUI code.

On the other hand if old users are relying on the deletion behaviour
(could it cause actual bad behaviour if this changes without them
realising it?) I suppose it is not good to change the behaviour either..
- Generally keeping a window around won't be that harmful but I guess in
  some instances the window may keep processing stuff in the background
  that the user wanted it to stop doing, so it may result in undesirable
  behaviour in some cases? (How common?)

So I'm not entirely sure if we should:
1) Preserve old behaviour of wxAuiNotebook - i.e. always set
optionDestroyOnClose by default on notebook panes.
2) Just document this better and/or explicitly mention the break in
behaviour in the changelog.
Either way we should probably document this somehow.

What is everyone elses thoughts on this?

**Comment by robertop** [comment]
Hi,
I was able to confirm that setting AUI pane option, but it took me a fair amount  of debugging to figure out that it had to be set it on the notebook's internal AUI manager, not the "main" AUI manager. Something like this:

```
notebook->GetAuiManager().GetPane(page).DestroyOnClose(true);
```

**Comment by mjmacleod** [comment]
Okay thanks.

As per previous response, it isn't 100% clear to me what we should do about this so I would like to hear some more opinions.
wxAuiNotebook should maybe have a GetPageInfo function to get the pane info directly without accessing the manager, the documentation should probably talk about close behaviour a bit to make it more clear. I'm not sure if we should go for backwards compatibility here or not?

**Comment by pkulchenko** [comment]
> 1) Preserve old behaviour of wxAuiNotebook - i.e. always set optionDestroyOnClose by default on notebook panes.

This would be my preference. I have a quite complex application (an IDE) and never felt any need to change (old) default values.

**Comment by nhold** [comment]
I agree, it should be backwards compatible considering wxWidgets prefers that over anything else. We should however document this and recommend setting it to false if they want their perspective to stay correct without any extra work.

**Comment by pkulchenko** [comment]
@nhold, thank you for the update. I plan to re-test with the updated version shortly.

**Comment by nhold** [comment]
I am closing this issue as it seems done, let me know if you think there is more that needs to be done.
