### ISSUE TITLE
Tabs order does not respect the add order of the panes

### ISSUE THREAD

**Issue by Kinaou** [nhold/wxWidgets#83]
The panes added programmatically to a identical direction (notebook created) are added sometimes at the beginning, sometimes at the end of the tabs container.

**Comment by Kinaou** [comment]
The cause is multiple.

Already, `wxAuiPaneInfo::m_dock_page` default value is zero. So all newly added panes are added at the first position in the tabs container. This behavior it's coherent but not very usual.

Then, at the rebuild of the notebook in `wxAuiManager::LayoutAddDock`, the insertion of the panes in the tabs container (`wxAuiTabContainer::InsertPage`) doesn't really care about the page number. If several panes, for some reason, have the same `m_dock_page` number, the first duplicate encountered will see its page number incremented at each new insertion and will end at the end of the tabs container.

**Comment by mjmacleod** [comment]
Do I understand correctly that #84 fixed this, or is there still some issue remaining here?
