### ISSUE TITLE
Floating panes are arbitrarily docked in LoadPerspective

### ISSUE THREAD

**Issue by Kinaou** [nhold/wxWidgets#92]
A pane which is dockable but currently floating is arbitrarily docked in `wxAuiManager::LoadPerspective`.
It was already an issue some times ago for dockable (but not floating) panes, but it seem that floating panes was forgotten: http://trac.wxwidgets.org/ticket/12648

I don't know why that was done, but whatever is the reason, the flags of the panes are now (in aui-dynamic-notebook branch) saved in the `state` value which restores properly the panes state.
The docking of the panes is thus useless now.

**Comment by nhold** [comment]
Merged your fix, thanks!
