### ISSUE TITLE
Focus is given to main frame after a tab selection instead of letting it in the contained window

### ISSUE THREAD

**Issue by Kinaou** [nhold/wxWidgets#94]
In wx30, when a `wxAuiNotebook` contains several text editors having the focus, the fact of changing of tab keeps the focus in the text editor selected.
In the aui-dynamic-notebook branch the focus is systematically given to the main frame.

On MSW the method `wxWindowMSW::MSWHandleMessage` (`window.cpp`) gives the focus to the calling object if the event sent when the left mouse button is pressed is skipped:

```
            wxWindowMSW *win = this;
            processed = win->HandleMouseEvent(message, x, y, wParam);

            // if the app didn't eat the event, handle it in the default
            // way, that is by giving this window the focus
            if ( !processed )
            {
                // for the standard classes their WndProc sets the focus to
                // them anyhow and doing it from here results in some weird
                // problems, so don't do it for them (unnecessary anyhow)
                if ( !win->IsOfStandardClass() )
                {
                    if ( message == WM_LBUTTONDOWN && win->IsFocusable() )
                        win->SetFocus();
                }
            }
```

and the equivalent for GTK in `gtk_window_button_press_callback`:

```
bool ret = win->GTKProcessEvent( event );
g_lastMouseEvent = NULL;
if ( ret )
    return TRUE;

if ((event_type == wxEVT_LEFT_DOWN) && !win->IsOfStandardClass() &&
    (gs_currentFocus != win) /* && win->IsFocusable() */)
{
    win->SetFocus();
}
```

In wx30, the method `wxAuiTabCtrl::OnLeftDown` does not skip the event and the focus is kept in the selected tab.
In the aui-dynamic-notebook branch, the method `wxAuiManager::OnLeftDown` (which reimplements the behavior) skips arbitrarily the event.

**Comment by mjmacleod** [comment]
Looks good to me.

**Comment by nhold** [comment]
"It still remains a minor issue when moving a tab with its window which has the focus from a notebook area to another: the tab's window loses the focus."

This should be a future thing, I'll create a specific issue for it.
